stages:
  make_dataset:
    cmd: python src/data/make_dataset.py
    deps:
      - src/data/make_dataset.py
    params:
      - make_dataset.test_size
      - make_dataset.random_state
    outs:
      - data/raw

  build_bert_features:
    cmd: python src/features/build_bert_feature.py
    deps:
      - src/features/build_bert_feature.py
      - data/raw
    params:
      - build_bert_features.model_name
      - build_bert_features.max_length
    outs:
      - data/interim/bert
  train_bert:
    cmd: python src/models/train_bert.py
    deps:
      - src/models/train_bert.py
      - data/interim/bert
    params:
      - train_bert.model_name
      - train_bert.num_labels
      - train_bert.epochs
      - train_bert.batch_size
      - train_bert.learning_rate
      - train_bert.eps
      - train_bert.seed
    outs:
      - model/bert
    metrics:
      - reports/bert_metrics.json:
          cache: false
    

  model_evaluation:
    cmd: python src/visualization/model_eval.py
    deps:
      - src/visualization/model_eval.py
      - model/bert
      - data/interim/bert
    params:
      - train_bert.model_name
      - train_bert.num_labels
    metrics:
      - reports/eval_metrics.json:
          cache: false
    outs:
      - reports/experiment_info.json:
          cache: false
