make_dataset: 
  test_size: 0.2
  random_state: 42

data_preprocessing:
  remove_stopwords: true
  keep_negations: ["not", "but", "however", "no", "yet"]
  lemmatize: true

build_features:
  max_features: 1000
  ngram_range: [1, 3]
  random_state: 42

train_model:
  kernel: poly
  C: 0.09669146694016018
  gamma_type: value
  gamma: 0.44466289554754435
  degree: 4
  coef0: 0.8872127425763265
  class_weight: null
  random_state: 42
  
build_bert_features:
  model_name: bert-base-uncased
  max_length: 256

train_bert:
  model_name: bert-base-uncased
  num_labels: 3
  epochs: 3
  batch_size: 16
  learning_rate: 0.00001
  eps: 0.00000001
  seed: 8